### PR TITLE
Update and rename Whonix_network.xml to internal_network.xml

### PR DESCRIPTION
**Pull request by HulaHoopWhonix**

### CODE REVIEW

**Comment by adrelanos** [comment]
Please grep all Whonix code for the old file names and change the name to the new names, otherwise it will break the build process.

**Comment by HulaHoopWhonix** [comment]
Done. They are a part of the new pull requests.

**Comment by adrelanos** [comment]
Not done. This at least also needs to be changed here:

https://github.com/Whonix/Whonix/blob/2a35f32f3e69ab8b324b671b8d01185d16d96802/help-steps/variables#L328

Please make sure this does not break the build.

**Comment by HulaHoopWhonix** [comment]
I have no idea what changes need to be done to the build script without breaking it. My guess is it needs to recognize two variables for the network files.

**Comment by adrelanos** [comment]
HulaHoopWhonix:

> I have no idea what changes need to be done to the build script without breaking it. My guess is it needs to recognize two variables for the network files.
- content of libvirt_source_network_file needs to be updated (similar
  for target file)
- libvirt_source_network_file should be renamed to
  libvirt_source_internal_network_file (similar for target file)
- variable libvirt_source_network_file should be added (similar for target)
- below the existing copy command in build-steps.d/1150_export-libvirt-xml
- also function libvirt_compress in
  https://github.com/Whonix/whonix-developer-meta-files/blob/master/release/prepare_release
  needs to be modified (update variable name, add the new external network
  file)

I am also very likely to break something during the development of
things. That's why this needs to be tested.

**Pull request merged**
